### ISSUE TITLE
Explanation please

### ISSUE THREAD

**Issue by togo59** [JuliaMPC/NLOptControl.jl#10]
Trying to understand the acronyms: EP; Internal EP (why is it IPEP); IP; etc. IP Initial problem? Interior point? Could the acronyms be explained in the documentation? Thank you.

**Comment by huckl3b3rry87** [comment]
@togo59 thank you for your question and interest in my package. 

First, I made a disclaimer at  the [beginning of the documentation
](https://juliampc.github.io/MPCDocs.jl/latest/mpc/index.html) that said that the documentation is not complete, but you may have missed it. 

Second, the MPC functionality is not complete. While a particular subset of it works the vision that I had for the whole framework was not finished. The difference between IP and EP is that IP stands for internal plant. In this case, you have defined your plant model in julia. While EP stands for external plant and that means that there the plant is either a model outside of julia or the actual physical plant. 

If you are interested in helping me develop this or have suggestions for it, please let me know!

**Comment by togo59** [comment]
Thank you for the explanation. I will have a go at using your package and if I get proficient enough I may be able to help. I am modelling a 10m long articulated boom with 6 very complicated joints comprising various gearbox types and motor types. The aim being to control it dynamically.

**Comment by huckl3b3rry87** [comment]
No problem! 

Sounds like a cool application, hopefully, you can solve your problem quickly enough to be used in real-time! Also, I noticed that you are commenting on RobotOS.jl. I also used that package along with NLOptControl and for an example you can see
https://github.com/JuliaMPC/MAVs
