### ISSUE TITLE
Example in tutorial.ipynb failed with errors

### ISSUE THREAD

**Issue by Flancis** [JuliaMPC/NLOptControl.jl#11]
Hi,

I was trying to run the examples given in the `tutorial.ipynb`. However, when I try to run the fourth line `n=define(de;numStates=3,numControls=1,X0=X0,XF=XF);`, it failed with following errors:
ERROR: MethodError: no method matching define(::Array{Expr,1}; numStates=3, numControls=1, X0=[0.0, 0.0, 0.0], XF=[2.0, -2.0, NaN])
Closest candidates are:
  define(; numStates, numControls, X0, XF, XL, XU, CL, CU) at C:\Users\XX\.julia\v0.6\NLOptControl\src\setup.jl:23

I am using Julia-0.6.4 on Windows 10, and the required packages were installed according to the given instructions.

Any help would be appreciated.

Francis

**Comment by huckl3b3rry87** [comment]
This is mentioned in the documentation
https://juliampc.github.io/MPCDocs.jl/stable/#juliaCon-Workshop-Notebook-(OUT-OF-DATE!)-1

There are also plenty of examples there.
