### ISSUE TITLE
Problem in running Quick EX#1

### ISSUE THREAD

**Issue by dongyy1148** [JuliaMPC/NLOptControl.jl#12]
I ran the Quick EX#1 wrote on the stable document by the Julia 0.6.4 on MAC OS.

The code is:
using NLOptControl, PrettyPlots
X0=[0.0,0.0,0.0]
XF=[2.,-2.,NaN]
n=define(numStates=3,numControls=1,X0=X0,XF=XF)
states!(n,[:x,:y,:v],descriptions=["x(t)","y(t)","v(t)"])
controls!(n,[:u],descriptions=["u(t)"])
dx=[:(v[j]*sin(u[j])),:(-v[j]*cos(u[j])),:(9.81*cos(u[j]))]
dynamics!(n,dx)
n.s.ocp.evalCostates = true
configure!(n;(:Nck=>[100]),(:finalTimeDV=>true));
@NLobjective(n.ocp.mdl,Min,n.ocp.tf)
optimize!(n);

Then I got the warning like this:
WARNING: Ipopt finished with status Restoration_Failed
Warning: Not solved to optimality, status: Error
WARNING: The solution is not Optimal 
Setting: n.f.mpc.simFailed = [true, n.r.ocp.status] 
ERROR: ArgumentError: New columns must have the same length as old columns

And there is no result shown.

**Comment by huckl3b3rry87** [comment]
please put your code in quotes. like ``this``

What version of NLOptControl are you using?
```
Pkg.status("NLOptControl")
```

**Comment by huckl3b3rry87** [comment]
This was fixed on the master branch in my latest commit 
https://github.com/JuliaMPC/NLOptControl.jl/commit/a06c2e24a9f5124856d69816584772567b54299b

Please use the master branch
```
Pkg.checkout("NLOptControl")
```

Please let me know if this fixes your issue

**Comment by huckl3b3rry87** [comment]
@dongyy1148 got
```
- NLOptControl                  0.1.6              0269a566 (dirty)
```
@dongyy1148 that means that you changed something in the package. You need to either undo those changes or just delete the package and add it again if you cannot figure that out

**Comment by dongyy1148** [comment]
Yeah. I also think so. So I have removed it and added it to try it again. But it still didn't work.
Besides, it's very weird that when I inputed:

>  Pkg.rm("NLOptControl")

It returned:

> INFO: No packages to install, update or remove
> INFO:Package database updated

But it was actually removed when I check by 

> Pkg.status()

And then I added it again and checked its status, it still gave me 

> - NLOptControl                  0.1.6              0269a566 (dirty)

Does I remove it wrongly?

**Comment by huckl3b3rry87** [comment]
you are running into basic julia usage issues. Please google these things and become familiar with julia

https://discourse.julialang.org/t/how-to-revert-dirty-packages/2122

https://docs.julialang.org/en/v0.6.2/manual/packages/

**Comment by huckl3b3rry87** [comment]
You get it?

**Comment by dongyy1148** [comment]
Yeah. I am learning this now. I know how to make it in git, but not familiar with Julia.

**Comment by dongyy1148** [comment]
Ok. i think I get updated edition now!
