### ISSUE TITLE
About the installation

### ISSUE THREAD

**Issue by johnysy** [JuliaMPC/NLOptControl.jl#13]
Hi!

I have trouble in using the package. I tried to add it but it failed by using Pkg.add() directly. But I can still add it by using Pkg.clone(). But then I can't clone the VehicleMod
![status](https://user-images.githubusercontent.com/32998009/51575683-0715e280-1e81-11e9-93bb-1c43578e790c.PNG)
![successinclone](https://user-images.githubusercontent.com/32998009/51575684-0715e280-1e81-11e9-84fb-65210e6c4511.PNG)
![troubleinvehiclemodels](https://user-images.githubusercontent.com/32998009/51575685-07ae7900-1e81-11e9-85bd-2a1a2163ae4e.PNG)
![troubleshooting1](https://user-images.githubusercontent.com/32998009/51575686-07ae7900-1e81-11e9-9b2b-c60f0d21cf2e.PNG)
![failure_in_using](https://user-images.githubusercontent.com/32998009/51575687-07ae7900-1e81-11e9-917d-f92acc20a12d.PNG)

els package

**Comment by huckl3b3rry87** [comment]
I have had trouble running Julia through Atom in the past, try running
directly through the terminal.

**Comment by johnysy** [comment]
Well, it seems that I can install the package NLOptControl right now, but I still can't use the VehicleModels package and the NLOptContol. The status shows that the package is installed, but julia is reporting errors. I ran this in Windows cmd like I did in C++.
![pq](https://user-images.githubusercontent.com/32998009/51583164-494d1d00-1e9d-11e9-99a8-33f53d922a73.PNG)

**Comment by huckl3b3rry87** [comment]
I am sorry, VehicleModels was moved to MichiganAutonomousVehicles.jl

**Comment by johnysy** [comment]
I can install the two packages. But I still can't run the Pkg.test() to MichiganAutonomousVehicles..Sorry to bother you this long!

**Comment by johnysy** [comment]
this is the error I am having right now
![test](https://user-images.githubusercontent.com/32998009/51586632-0181c200-1eac-11e9-836f-ce8b6768fb9a.PNG)

**Comment by huckl3b3rry87** [comment]
Did you figure this out? sorry for the delay
