### ISSUE TITLE
Is it working on julia 1.0?

### ISSUE THREAD

**Issue by danielchen26** [JuliaMPC/NLOptControl.jl#14]
I tried to install it. But it gives me error as below:
(v1.0) pkg> add NLOptControl
 Resolving package versions...
ERROR: Unsatisfiable requirements detected for package NLOptControl [290757bd]:
 NLOptControl [290757bd] log:
 ├─possible versions are: 0.1.2-0.1.6 or uninstalled
 ├─restricted to versions * by an explicit requirement, leaving only versions 0.1.2-0.1.6
 ├─restricted by compatibility requirements with DataFrames [a93c6f00] to versions: 0.1.4-0.1.6 or uninstalled, leaving only versions: 0.1.4-0.1.6
 │ └─DataFrames [a93c6f00] log:
 │   ├─possible versions are: [0.1.0, 0.2.0-0.2.5, 0.3.0-0.3.16, 0.4.0-0.4.3, 0.5.0-0.5.12, 0.6.0-0.6.11, 0.7.0-0.7.8, 0.8.0-0.8.5, 0.9.0-0.9.1, 0.10.0-0.10.1, 0.11.0-0.11.7, 0.12.0, 0.13.0-0.13.1, 0.14.0-0.14.1, 0.15.0-0.15.2, 0.16.0, 0.17.0] or uninstalled
 │   └─restricted to versions 0.17.0 by an explicit requirement, leaving only versions 0.17.0
 └─restricted by julia compatibility requirements to versions: uninstalled — no versions left

**Comment by johnysyumich** [comment]
no, it works on Julia 0.6.4

**Comment by huckl3b3rry87** [comment]
it does not work on 1.0
