### ISSUE TITLE
About nonlinear constrain

### ISSUE THREAD

**Issue by johnysyumich** [JuliaMPC/NLOptControl.jl#15]
Hi!

How can we define a nonlinear constrain and solved it by using NLOptControl?

Can you provide some examples?

Thanks

**Comment by huckl3b3rry87** [comment]
Here is an old example that I had in the docs but depreciated 
https://github.com/JuliaMPC/NLOptControl.jl/blob/master/docs/old/KinematicBicycle/main.md

Here is another example that is currently working, but not documented 
https://github.com/JuliaMPC/MichiganAutonomousVehicles.jl/blob/master/src/AutonomousControl.jl#L340
