### ISSUE TITLE
How to set the final destination as a hard constrain

### ISSUE THREAD

**Issue by johnysyumich** [JuliaMPC/NLOptControl.jl#16]
Hi!
I got a problem when I am using the dynamic bicycle, when I set the cost function to just final time. The vehicle would not move anymore unless I included the final destination in the cost function. If I wanted to set the destination in the XF and I include a obstacle, the error would show that the new column doesn't have the same length as the old column. why is that

**Comment by huckl3b3rry87** [comment]
This question is not really specific to NLOptControl.jl, it is better suited for MichiganAutonomousVehicles.jl. Please ask this question [here](https://github.com/JuliaMPC/MichiganAutonomousVehicles.jl). Also, include a minimum working example (MWE). I understand your question, but there should not be an issue doing what you are asking. It sounds like you have some sort of bug, which is impossible for me to figure out with the information that you have provided. 

Thanks
