### ISSUE TITLE
enabling scaling of the states and controls

### ISSUE THREAD

**Issue by huckl3b3rry87** [JuliaMPC/NLOptControl.jl#17]
I am developing functionality to enable the user to easily scale the states and control variables inside the NLP - scaling affects convergence, numerical conditioning, and termination tests. 

A preliminary version of of this functionality in NLOptControl enables this, however, several of the tests are breaking. 

Consider the example:
```
using NLOptControl
BrysonDenham_EXP=[:(x2[j]),:(u1[j])]; L=1/6;
integrationConfig = :trapezoidal 
n=define(numStates=2,numControls=1,X0=[0.,1],XF=[0.,-1.],XL=[0.,NaN],XU=[L,NaN]);
dynamics!(n,BrysonDenham_EXP)
configure!(n;(:integrationScheme=>integrationConfig),(:finalTimeDV=>false),(:tf=>1.0));
obj=integrate!(n,:(0.5*u1[j]^2));
@NLobjective(n.ocp.mdl,Min,obj);
optimize!(n);
@show n.r.ocp.dfsOpt[:tSolve]
@show 4/(9*L)
@show n.r.ocp.objVal[1]
``` 
Before [this commit ](https://github.com/JuliaMPC/NLOptControl.jl/commit/d6d455b5f742a6dbe5e5c64a5e94011f44e6024f), the objective function values were very close and tests where passing and the solution looks like this
![before](https://user-images.githubusercontent.com/8204378/59139865-2d797d80-894b-11e9-9198-0d11136a5e83.png)

However, after turning the variables into ``@NLexpression()``s so they can be used later with the scaling factor, which is set to one for this example, the trajectory looks like this 

![jump](https://user-images.githubusercontent.com/8204378/59139883-6dd8fb80-894b-11e9-8d4f-eb755dab77a3.png)

 I am having trouble figuring out why this is happening. It only happens when I change
```
 n.r.ocp.x = x
```
To 
```
  n.r.ocp.x = Matrix{Any}(n.ocp.state.pts,n.ocp.state.num)
  for st in 1:n.ocp.state.num
      n.r.ocp.x[:,st] = @NLexpression(n.ocp.mdl, [j=1:n.ocp.state.pts], n.ocp.XS[st]*x[j,st])
  end
```
and the same type of change for the control variable.

and then
```
function DiffEq(n::NLOpt,x::Array{JuMP.Variable,2},u::Array{JuMP.Variable,2},L::Int64,st::Int64)
```
to 
```
function DiffEq(n::NLOpt,x::Array{Any,2},u::Array{Any,2},L::Int64,st::Int64)
```

and finally
```
function addCon(n::NLOpt,x::Array{Any,2},u::Array{Any,2},L::Int64,num::Int64)
```
to
```
function addCon(n::NLOpt,x::Array{JuMP.Variable,2},u::Array{JuMP.Variable,2},L::Int64,num::Int64)
```

So, effectively, I am creating a whole bunch of new ``@NLexpression()``s and then nesting them. I know that this is not a very elegant solution, but I cannot understand the problem.

@tkelman or @ChrisRackauckas  or @mlubin  @blegat  

I know that this is likely confusing thing, but if any of you mind taking a look to see if you can figure out what I  am doing wrong, I would greatly appreciate it.

Thanks!

**Comment by mlubin** [comment]
@huckl3b3rry87 We recently fixed [a bug](https://github.com/JuliaOpt/JuMP.jl/pull/1979) related to nested subexpressions. Could you try using JuMP `master`?

**Comment by huckl3b3rry87** [comment]
@mlubin wow, this is great news! I think that I may have encountered this a while back as well and just avoided the nested subexpressions.

Unfortunately, I have not had time to upgrade NLOptControl past using julia 0.6, so I am stuck at JuMP 0.18.4.

Back when [this functionality ](https://github.com/mlubin/ReverseDiffSparse.jl/blob/v0.8.4/src/subexpressions.jl#L20) was in ReverseDiffSparse, of which, I am using 0.8.4.

I just added your fix to ReverseDiffSparse.jl and it worked!!!!! Wow, thanks for fixing this, I never would have figured it out....

I just made a [pull request](https://github.com/mlubin/ReverseDiffSparse.jl/pulls) to ReverseDiffSpare.jl with these changes. Do you mind merging it?

Thanks again!!
