### ISSUE TITLE
NLOptControl and KNITRO

### ISSUE THREAD

**Issue by JaviBonilla** [JuliaMPC/NLOptControl.jl#19]
I am quite new to Julia and NLOptControl.jl. I am trying to install it on Julia 0.7, but when building the NLOptControl.jl package I get this error.

`ERROR: LoadError: Unable to locate KNITRO installation, please check your enviroment variable KNITRODIR.`

Is KNITRO required? I thought that IPOPT.jl could be used instead.

Thanks.

**Comment by huckl3b3rry87** [comment]
It can be used without KNITRO, NLOptControl does not work for julia 0.7,
you have to use Julia 0.6, look at the .travis file

**Comment by JaviBonilla** [comment]
Ok, it is working on Julia 0.6.

Thanks @huckl3b3rry87!

**Comment by huckl3b3rry87** [comment]
No problem!
