### ISSUE TITLE
Defining Dynamics Model

### ISSUE THREAD

**Issue by jshan432** [JuliaMPC/NLOptControl.jl#20]
Do the dynamics have to be written as an array of differential equation expressions? I've got a few problems with pretty complex dynamic models that would be much easier to represent in a separate function. GPOPS has been my go to solver thus far, but I'd like to try NLOptControl for the increased speed. 

Thanks, 

Jackson

**Comment by huckl3b3rry87** [comment]
Yes, currently they need to be expression. But you can define complicated expressions separately and then evaluate them in the array
https://juliampc.github.io/NLOptControl.jl/latest/tutorials/RobotArm/main.html

or see
https://github.com/JuliaMPC/MichiganAutonomousVehicles.jl/blob/master/src/VehicleModels/Three_DOF/Three_DOF.jl#L113
