### ISSUE TITLE
Starting point for optimization

### ISSUE THREAD

**Issue by johnysyumich** [JuliaMPC/NLOptControl.jl#21]
We're currently working on feeding a solution to the solver to avoid local minimum, I checked the documentation, but I didn't find where to change it. 

Thanks for your help

**Comment by huckl3b3rry87** [comment]
This functionality is available through JuMP API, please check that

**Comment by huckl3b3rry87** [comment]
http://www.juliaopt.org/JuMP.jl/v0.18/nlp.html?highlight=setvalue#nonlinear-parameters
