### ISSUE TITLE
package not found with Pkg.add()

### ISSUE THREAD

**Issue by mishapadidar** [JuliaMPC/NLOptControl.jl#23]
Pkg.add("NLOptControl") is not successfully installing the package. Julia 1.0.5 is giving the error

ERROR: The following package names could not be resolved:
 * NLOptControl (not found in project, manifest or registry)
Please specify by known `name=uuid`.

Could you give some insight to this?

**Comment by huckl3b3rry87** [comment]
Unfortunately, NLOptControl was not updated with julia and only works with julia 0.6. I will update the README to add installation instructions for julia 0.6
