### ISSUE TITLE
Key error

### ISSUE THREAD

**Issue by ntregloh** [JuliaMPC/NLOptControl.jl#28]
I've just installed NLOptControl to Julia 0.6.4 and I am trying out the examples, which seem to run. 
However, when I enter 

julia> allPlots(n)

I get the error below, for which I have no idea what to do (I installed all 3 plotting backends mentioned in the tutorial).

Thanks.
 
Error showing value of type Plots.Plot{Plots.PyPlotBackend}:
ERROR: KeyError: key 1 not found
Stacktrace:
 [1] getindex(::Dict{String,Any}, ::Int64) at ./dict.jl:474
 [2] render(::Juno.PlotPane, ::Plots.Plot{Plots.PyPlotBackend}) at /Users/hteisman/.julia/v0.6/Plots/src/output.jl:330
 [3] display(::Media.DisplayHook, ::Plots.Plot{Plots.PyPlotBackend}) at /Users/hteisman/.julia/v0.6/Media/src/compat.jl:9
 [4] display(::Plots.Plot{Plots.PyPlotBackend}) at ./multimedia.jl:218
 [5] eval(::Module, ::Any) at ./boot.jl:235
 [6] print_response(::Base.Terminals.TTYTerminal, ::Any, ::Void, ::Bool, ::Bool, ::Void) at ./REPL.jl:144
 [7] print_response(::Base.REPL.LineEditREPL, ::Any, ::Void, ::Bool, ::Bool) at ./REPL.jl:129
 [8] (::Base.REPL.#do_respond#16{Bool,Atom.##150#151,Base.REPL.LineEditREPL,Base.LineEdit.Prompt})(::Base.LineEdit.MIState, ::Base.AbstractIOBuffer{Array{UInt8,1}}, ::Bool) at ./REPL.jl:646

**Comment by huckl3b3rry87** [comment]
Can you provide the exact code that you ran as well as the current versions of your software? i.e.,
```
Pkg.status()
```

**Comment by ntregloh** [comment]
> Can you provide the exact code that you ran as well as the current versions of your software? i.e.,
> 
> ```
> Pkg.status()
> ```

Please see below. Thanks!

Code

`using NLOptControl
using PrettyPlots

n = define(numStates=2,numControls=1,X0=[10.,-2],XF=[0.,0.],CL=[0.],CU=[3.])
states!(n,[:h,:v];descriptions=["h(t)","v(t)"])
controls!(n,[:T];descriptions=["T(t)"])
dx=[:(v[j]),:(T[j]-1.625)]
dynamics!(n,dx)
configure!(n;(:finalTimeDV=>true));
obj = integrate!(n,:(T[j]))
# Now this term can be added as the objective function and the problem can be solved
@NLobjective(n.ocp.mdl, Min, obj);
optimize!(n)
allPlots(n)`

Status

`julia> Pkg.status()
9 required packages:
 - Atom                          0.6.17
 - GR                            0.39.0
 - Ipopt                         0.4.5
 - Juno                          0.4.1
 - KNITRO                        0.4.0              pinned.849aef25.tmp
 - NLOptControl                  0.1.6              0269a566 (dirty)
 - PGFPlots                      2.2.2
 - PrettyPlots                   0.0.3
 - PyPlot                        2.7.0
137 additional packages:
 - ASTInterpreter2               0.1.1
 - AbstractFFTs                  0.3.2
 - AssetRegistry                 0.0.2
 - AxisAlgorithms                0.3.0
 - AxisArrays                    0.2.1
 - BinDeps                       0.8.10
 - BinaryProvider                0.3.3
 - Blink                         0.7.0
 - CSV                           0.2.5
 - Calculus                      0.4.1
 - CatIndices                    0.1.0
 - CategoricalArrays             0.3.13
 - CodeTools                     0.5.1
 - CodecZlib                     0.4.4
 - ColorBrewer                   0.3.1
 - ColorTypes                    0.6.7
 - ColorVectorSpace              0.5.2
 - Colors                        0.8.2
 - CommonSubexpressions          0.1.0
 - Compat                        2.2.0
 - ComputationalResources        0.2.0
 - Conda                         1.0.2
 - Contour                       0.4.0
 - CoordinateTransformations     0.5.0
 - CustomUnitRanges              0.1.0
 - DataFrames                    0.11.7
 - DataStreams                   0.3.8
 - DataStructures                0.8.4
 - DebuggerFramework             0.1.2
 - DiffBase                      0.3.2
 - DiffEqBase                    3.13.3
 - DiffEqDiffTools               0.4.1
 - DiffEqOperators               1.3.0
 - DiffResults                   0.0.4
 - DiffRules                     0.0.10
 - Discretizers                  2.1.0
 - Distances                     0.6.0
 - DocSeeker                     0.1.0
 - FFTViews                      0.1.0
 - FFTW                          0.0.4
 - FastGaussQuadrature           0.3.3
 - FileIO                        0.9.1
 - FixedPointNumbers             0.4.6
 - ForwardDiff                   0.7.5
 - FunctionWrappers              1.0.0
 - FunctionalCollections         0.3.2
 - GenericSVD                    0.1.0
 - Graphics                      0.4.0
 - Hiccup                        0.1.1
 - Homebrew                      0.6.6
 - HttpCommon                    0.4.0
 - HttpParser                    0.4.0
 - HttpServer                    0.3.1
 - IdentityRanges                0.1.0
 - ImageAxes                     0.4.0
 - ImageCore                     0.6.0
 - ImageDistances                0.0.2
 - ImageFiltering                0.3.0
 - ImageMagick                   0.5.2
 - ImageMetadata                 0.4.3
 - ImageMorphology               0.0.2
 - ImageTransformations          0.4.2
 - Images                        0.14.0
 - IndirectArrays                0.4.2
 - InternedStrings               0.6.2
 - Interpolations                0.8.0
 - IntervalSets                  0.2.1
 - IterTools                     0.2.1
 - IteratorInterfaceExtensions   0.0.2
 - JSExpr                        0.2.2
 - JSON                          0.17.2
 - JuMP                          0.18.5
 - LNR                           0.0.2
 - LaTeXStrings                  1.0.3
 - Lazy                          0.12.1
 - LineSearches                  4.0.0
 - LinearMaps                    1.0.4
 - MacroTools                    0.4.5
 - MappedArrays                  0.0.7
 - MathOptInterface              0.8.4
 - MathProgBase                  0.7.7
 - MbedTLS                       0.5.14
 - Measures                      0.2.0
 - Media                         0.3.0
 - Missings                      0.2.10
 - MuladdMacro                   0.0.2
 - Mustache                      0.3.3
 - Mux                           0.3.1
 - NLSolversBase                 4.4.1
 - NLsolve                       1.1.1
 - NaNMath                       0.3.2
 - NamedTuples                   4.0.2
 - Nullables                     0.0.8
 - Observables                   0.1.2
 - OffsetArrays                  0.6.0
 - OrdinaryDiffEq                3.21.0
 - PaddedViews                   0.3.0
 - Parameters                    0.9.2
 - Pidfile                       1.0.0
 - PlotThemes                    0.2.0
 - PlotUtils                     0.4.4
 - Plots                         0.17.4
 - ProgressMeter                 0.5.6
 - PyCall                        1.18.5
 - RangeArrays                   0.3.1
 - Ratios                        0.3.1
 - RecipesBase                   0.3.1
 - RecursiveArrayTools           0.15.0
 - Reexport                      0.1.0
 - Requires                      0.4.4
 - ReverseDiffSparse             0.8.6
 - Roots                         0.7.4
 - Rotations                     0.7.2
 - SHA                           0.5.7
 - SIUnits                       0.1.0
 - ShowItLikeYouBuildIt          0.2.0
 - Showoff                       0.2.1
 - SimpleTraits                  0.6.0
 - SortingAlgorithms             0.2.1
 - SpecialFunctions              0.6.0
 - StaticArrays                  0.7.2
 - StatsBase                     0.23.1
 - StringDistances               0.2.1
 - TableTraits                   0.2.0
 - TexExtensions                 0.1.0
 - TikzPictures                  1.2.0
 - TiledIteration                0.1.0
 - Tokenize                      0.4.2
 - TranscodingStreams            0.5.4
 - URIParser                     0.3.1
 - VehicleModels                 0.1.4
 - VersionParsing                1.1.3
 - WeakRefStrings                0.4.7
 - WebIO                         0.2.8
 - WebSockets                    0.5.0
 - Widgets                       0.2.5
 - WoodburyMatrices              0.3.0`

**Comment by huckl3b3rry87** [comment]
Your PyPlot version matches the version that that documentation is built with '
https://api.travis-ci.org/v3/job/657586768/log.txt

But your version of NLOptControl is older. Also you made changes to NlOptControl, as it is dirty.

So, 
1) get ride of your changes or simply remove NLOptControl
2) update NLOptControl to the master,
If you just got ride of yoru changes something like
```
Pkg.checkout(`NLOptControl`)
```
If you simply removed it
```
Pkg.clone('NLOptControl')
```
Then check the status again to make sure that it it the master

**Comment by ntregloh** [comment]
Thanks. Unfortunately after removing NLOptControl and running Pkg.clone("NLOptControl"), the error persists. 
The master version is installed  but it is still labelled "dirty" 

 julia> Pkg.status("NLOptControl")
 - NLOptControl                  0.1.6+             master (dirty)  

(and I had not made any changes to the previous version either).

**Comment by huckl3b3rry87** [comment]
Looks like you are using Juno. Try running it from the terminal

**Comment by huckl3b3rry87** [comment]
@ntregloh have you had a change to try what I suggested? I remember Juno did not work for me either, I would just run from the terminal

**Comment by ntregloh** [comment]
Thanks for your suggestion. Unfortunately, still no luck. It is still shows a dirty installation of the master.

**Comment by huckl3b3rry87** [comment]
Delete it completely and reinstall it

**Comment by ntregloh** [comment]
I think I have to give up on this. It always comes back to a dirty version of the master. (Maybe it's an issue with the Mac-version of NLOptControl.jl (?)  So far, it appears that the computations are actually completing and the issue is only with prettyPlots and allPlots ... so maybe I can get by with doing the plotting etc. manually. 

Thanks for your help.

**Comment by huckl3b3rry87** [comment]
looking again you are using an old version from May 2018
https://github.com/JuliaMPC/NLOptControl.jl/commit/0269a566dc7b4c0e108dbb185d061a3ca99fea0d

Remove it and try 
```
Pkg.clone("https://github.com/JuliaMPC/NLOptControl.jl")
```

**Comment by huckl3b3rry87** [comment]
Also, just curious, what is your use case for NLOptControl?

**Comment by ntregloh** [comment]
Here is what I get. (Note that I have to run Pkg.rm twice to actually do anything ....)

julia> Pkg.status("NLOptControl.jl")
 - NLOptControl                  0.1.6+             master (dirty)

julia> Pkg.rm("NLOptControl")
INFO: No packages to install, update or remove
INFO: Package database updated

julia> Pkg.rm("NLOptControl")
INFO: Removing NLOptControl (unregistered)

julia> Pkg.status("NLOptControl.jl")

julia> Pkg.clone("https://github.com/JuliaMPC/NLOptControl.jl")
INFO: Cloning NLOptControl from https://github.com/JuliaMPC/NLOptControl.jl
INFO: Computing changes...
INFO: No packages to install, update or remove
INFO: Package database updated

julia> Pkg.status("NLOptControl.jl")
 - NLOptControl                  0.1.6+             master (dirty)

**Comment by ntregloh** [comment]
To your 2nd question: Covid-19-related research. Something along the lines of 
https://www.medrxiv.org/content/10.1101/2020.04.02.20049189v2

**Comment by huckl3b3rry87** [comment]
Very cool, delete it manually. It should be in the  ./julia folder.

**Comment by huckl3b3rry87** [comment]
Oops, forgot my last comment

**Comment by ntregloh** [comment]
I thought I'd figured out that ReverseDiffSparse was the problem, since the installation of NLOptControl would complain about it. So after re-installing Julia, I began by Pkg.clone("ReverseDiffSparse") to get the master version before running Pkg.clone("https://github.com/JuliaMPC/NLOptControl.jl")  That seemed to make the installation of NLOptControl go through without snag .... BUT eventually I got 

julia> Pkg.status("NLOptControl")
 - NLOptControl                  0.1.6+             master (dirty)

as before. As I said, I may just try to do things without using prettyPlots etc ...

**Comment by huckl3b3rry87** [comment]
do Pkg.status() again please

**Comment by huckl3b3rry87** [comment]
the problem is that you are using some old version, not sure why you are stuck on it, probably a req. thing.

try to remove everything and follow the .travis file instructions
https://github.com/JuliaMPC/NLOptControl.jl/blob/master/.travis.yml

the current build is using the latest version https://travis-ci.org/github/JuliaMPC/NLOptControl.jl

When you do get the actual latest version make sure you look at the latest documentation
https://juliampc.github.io/NLOptControl.jl/latest/tutorials/Brachistochrone/main.html

notice that there is not 
```
using PrettyPlots
```
I moved it into NLOptControl
