### ISSUE TITLE
Support for supplying initial guesses?

### ISSUE THREAD

**Issue by QuantumBits** [JuliaMPC/NLOptControl.jl#8]
Is there any way to supply an initial guess to this solver? I'm familiar with GPOPS-II in Matlab, and this was a functionality that I found pretty invaluable when attempting to solve certain problems.

**Comment by huckl3b3rry87** [comment]
Yes. It exports 
```
setvalue()
```
from JuMP

Here is an example:
https://github.com/JuliaMPC/NLOptControl.jl/blob/master/test/ocp.jl#L101

Where you have to pass the JuMP variable.

Notice how it is extracted
https://github.com/JuliaMPC/NLOptControl.jl/blob/master/test/ocp.jl#L98

**Comment by QuantumBits** [comment]
Oh perfect! I wasn't aware of that feature in JuMP! Thanks!

**Comment by huckl3b3rry87** [comment]
no problem!
