### ISSUE TITLE
Increasing number of obstacles algorithm can handle?

### ISSUE THREAD

**Issue by CGoodin** [JuliaMPC/NLOptControl.jl#9]
I'm running the "obstacle_avoidance.jl" script. If I increase the number of obstacles above 1, I get the warning "number of obstacles detected exceeds the number of obstacles the algorithm was designed for! Consider increasing the number of obstacles the algorithm can handle." How do I go about increasing the number of obstacles the algorithm can handle?

**Comment by huckl3b3rry87** [comment]
@CGoodin this is not related to this package
